server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
  port: 8080

spring:
  # H2 설정
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: x.frame
      default-receive-queue: q.frame
      routing-key: message

# Logging
logging:
  level:
    org:
      hibernate: info