server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
  port: 18080

spring:
  # H2 설정
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  # RabbitMQ 설정
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: xx.frame
      default-receive-queue: qq.frame
      routing-key: message

  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379

# Logging
logging:
  level:
    org:
      hibernate: info